### ISSUE TITLE
For help: Thanks for your fantastic work. Could you share the code which supports the Neuroscan system?

### ISSUE THREAD

**Issue by DayBright-David** [ludovicdmt/t9_ssvep#1]

**Comment by ludovicdmt** [comment]
Hello, 
Sorry currently we don't own any Neuroscan in the lab (didn't know the device before actually) so I don't have such code.

Although, the code was not meant to be specific to a device. 
EEG data are streamed using LabStreamingLayer (for your EEG device you can find the software here: <https://github.com/labstreaminglayer/App-Neuroscan>) and received trough an Inlet by the classification script using PyLSL. 

The only modifications you should do are probably to change the `DataStream` argument in the [classification script](https://github.com/ludovicdmt/t9_ssvep/blob/main/classification/online_T9.py) so it can connect properly and eventually [the downsampling factor](https://github.com/ludovicdmt/t9_ssvep/blob/main/classification/online_T9.py#L432) for TRCA if your EEG device has a sampling rate different from 500Hz (should be 250Hz after downsampling). 

The results could be different if the quality of the EEG signal (signal over noise ratio mainly) for Neuroscan is different from the high quality data that we have with the BrainProduct device.

Have a nice day.

**Comment by ludovicdmt** [comment]
You can find more details on the experimental setup in our open-access paper: https://www.nature.com/articles/s41598-022-12733-0

**Comment by DayBright-David** [comment]
> Hello, Sorry currently we don't own any Neuroscan in the lab (didn't know the device before actually) so I don't have such code.
> 
> Although, the code was not meant to be specific to a device. EEG data are streamed using LabStreamingLayer (for your EEG device you can find the software here: https://github.com/labstreaminglayer/App-Neuroscan) and received trough an Inlet by the classification script using PyLSL.
> 
> The only modifications you should do are probably to change the `DataStream` argument in the [classification script](https://github.com/ludovicdmt/t9_ssvep/blob/main/classification/online_T9.py) so it can connect properly and eventually [the downsampling factor](https://github.com/ludovicdmt/t9_ssvep/blob/main/classification/online_T9.py#L432) for TRCA if your EEG device has a sampling rate different from 500Hz (should be 250Hz after downsampling).
> 
> The results could be different if the quality of the EEG signal (signal over noise ratio mainly) for Neuroscan is different from the high quality data that we have with the BrainProduct device.
> 
> Have a nice day.

Thanks for your reply.
